<div class="container">
    <br><br><br>
    <div class="row">
        <div class="col-lg-12 text-center v-center">
            <h1>Oops!</h1>
            <h2>404 Not Found</h2>
            <p class="lead">A url solicitada "<code style="color: #196EEE;">/<?php echo @$_GET['uri']; ?></code>" não foi encontrada em nosso servidor.</p>
        </div>
    </div>
    <br><br><br><br>
    <br><br><br>
</div>