<!-------------------------------------------------------Banner------------------------------------------------------->
<div class="carousel slide" id="myCarousel">
    <ol class="carousel-indicators">
        <li class="active" data-slide-to="0" data-target="#myCarousel"></li>
        <li data-slide-to="1" data-target="#myCarousel" class=""></li>
    </ol>
    <div class="carousel-inner">
        <div class="item active">
            <img class="img-responsive" src="<?php echo $this->site_url('img/banner/2.png'); ?>">
            <div class="container">
                <div class="carousel-caption" style="text-shadow: 0 3px 5px rgba(0,0,0,.6)">
                    <h1>Dia 16 de Dezembro de 2014 as 11h e 45min</h1>
                    <h3 style="font-style: italic;">"Dia de sua volta! Falta só"</h3>
                    <div id="countdown"></div>
                    <p id="note"></p>
                    <!--<p><a href="#" class="btn btn-large btn-primary">Learn more</a></p>-->
                </div>
            </div>
        </div>
        <div class="item">
            <img class="img-responsive" src="<?php echo $this->site_url('img/banner/1.png'); ?>">
        </div>
    </div>
    <a data-slide="prev" href="#myCarousel" class="left carousel-control">
        <span class="icon-prev"></span>
    </a>
    <a data-slide="next" href="#myCarousel" class="right carousel-control">
        <span class="icon-next"></span>
    </a>  
</div>
	
<!-------------------------------------------------------Conteúdo------------------------------------------------------->
<div class="container" style="margin-bottom: 20px">
    <div class="row">
        <div class="col-md-6">
            <img class="img-circle col-md-12" src="<?php echo $this->site_url('img/sister-araujo.png');?>">
        </div>
        <div class="col-md-6">
            <h2 style="display: inline-block">Priscila Lima</h2>
            <h5 style="display: inline-block" class="text-muted">(<a><?php echo $this->site_titulo;?></a>)...</h5>
            <p class="text-justify">
                ...é missionária de <a href="https://www.lds.org/?lang=por" target="_blank">A IGREJA DE JESUS CRISTO DOS SANTOS DOS ÚLTIMOS DIAS</a> em períoso integral até que o contador acima chegue a zéro.
            </p>
        </div>
    </div>
</div>