<!-------------------------------------------------------Banner------------------------------------------------------->
<div class="carousel slide" id="myCarousel">
    <ol class="carousel-indicators">
        <li class="active" data-slide-to="0" data-target="#myCarousel"></li>
        <li data-slide-to="1" data-target="#myCarousel" class=""></li>
        <li data-slide-to="2" data-target="#myCarousel" class=""></li>
    </ol>
    <div class="carousel-inner">
        <div class="item active">
            <img class="img-responsive" src="<?php echo $this->site_url('img/banner/1.png'); ?>">
        </div>
        <div class="item">
            <img class="img-responsive" src="http://lorempixel.com/1500/600/abstract/1">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Changes to the Grid</h1>
                    <p>Bootstrap 3 still features a 12-column grid, but many of the CSS class names have completely changed.</p>
                    <p><a href="#" class="btn btn-large btn-primary">Learn more</a></p>
                </div>
            </div>
        </div>
        <div class="item">
            <img class="img-responsive" src="http://placehold.it/1500X500">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Percentage-based sizing</h1>
                    <p>With "mobile-first" there is now only one percentage-based grid.</p>
                    <p><a href="#" class="btn btn-large btn-primary">Browse gallery</a></p>
                </div>
            </div>
        </div>
    </div>
    <a data-slide="prev" href="#myCarousel" class="left carousel-control">
        <span class="icon-prev"></span>
    </a>
    <a data-slide="next" href="#myCarousel" class="right carousel-control">
        <span class="icon-next"></span>
    </a>  
</div>
	
<!-------------------------------------------------------Outro------------------------------------------------------->
<div class="container">
    <div class="row">
        <div class="col-md-7">
            <h1>Blog</h1>
            <p class="lead">Catchy Subtitle Here</p>
        </div>
        <div class="col-md-5">
            <div class="well well-lg"> 
                <div class="row">
                    <div class="col-sm-12">
                        Ad Space			
                    </div>
                </div>
            </div>
        </div>
    </div> 
</div>


<div class="container">
    <div class="row">
        <div class="col-md-12"> 
            <div class="panel">
                <div class="panel-body">
                    <div class="row">
                    </div>
                    <a href="/" class="btn btn-primary pull-right btnNext">More <i class="glyphicon glyphicon-chevron-right"></i></a>
                </div>
            </div>
   	</div>
    </div>
</div>