<div class="container">
    <div class="row">
        <div class="col col-sm-3">
            <div class="">
                <ul class="nav bs-docs-sidenav">
                    <li><h3 class="highlight">Vídeos <i class="fa fa-video-camera pull-right"></i></h3></li>
                    <li><a href="#"><i class="fa fa-film"></i> Mick Hill</a></li>
                    <li><a href="#"><i class="fa fa-youtube-play"></i> YouTube</a></li>
                </ul>
<!--                <div id="accordion2" class="accordion">
                    <div class="accordion-group">
                        <div class="accordion-heading">
                            <a href="#collapseOne" data-parent="#accordion2" data-toggle="collapse" class="accordion-toggle">
                                Accordion
                            </a>
                        </div>
                        <div class="accordion-body collapse in" id="collapseOne">
                            <div class="accordion-inner">
                              <p>There is a lot to be said about RWD.</p>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-group">
                        <div class="accordion-heading">
                            <a href="#collapseTwo" data-parent="#accordion2" data-toggle="collapse" class="accordion-toggle">
                                Accordion
                            </a>
                        </div>
                        <div class="accordion-body collapse" id="collapseTwo">
                            <div class="accordion-inner">
                                <p>Use @media queries or utility classes to customize responsiveness.</p>
                            </div>
                        </div>
                    </div>
                </div>-->
            </div>
        </div>  
        <div class="col col-sm-9">
            <div class="panel">
                <h1>Olá meu amor!!!</h1>
                <h5>Como vecê está? espero que bem.</h5>
                <img class="img-responsive" src="//placehold.it/150x100/EEEEEE">
                <div class="bs-example">
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe allowfullscreen="" src="//www.youtube.com/embed/-3kJTmQMhUw" class="embed-responsive-item"></iframe>
                    </div>
                </div>
        
                <p>Teste de texto</p>
                
                <!--<button class="btn btn-default">More</button>-->
                
                <hr>
                
                <div class="row">
                    <div class="col col-sm-6">
                        <img class="img-responsive" src="/assets/example/bg_smartphones.jpg">
                    </div> 
                    <div class="col col-sm-6">
                        <p>There is still a lot to be said about the Responsive Web.</p>
                    </div>   
                </div>
                
                <hr>
              
              	<h2>Responsive Text</h2>
      			Eeaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae 
                dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia cor magni dolores 
                eos qui ratione voluptatem sequi nesciunt. Bootply is this awesomeness. Editor, prototype tool, adipisci velit, 
                sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. 
                Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut
              
                <hr>
                
              	<h2>Responsive Images</h2>
      			Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, 
                totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae 
                dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia cor magni dolores 
                eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, 
                sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. 
                Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut
              
                <hr>
                
              	<h2>Media Queries</h2>
      			Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, 
                totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae 
                dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia cor magni dolores 
                eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, 
                sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. 
                Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut
              
              
              	<h1><a href="#"><i class="glyphicon glyphicon-user"></i> <i class="glyphicon glyphicon-chevron-down"></i></a></h1>
              
              	<hr>
              	<h4><a href="http://bootply.com/">Bootply</a></h4>
              	<hr>
             	</div>
      	</div> 
  	</div>
</div>