<div class="container">
    <div class="row">
        <div class="col col-sm-3">
            <div class="">
                <ul class="nav bs-docs-sidenav">
                    <li><h3 class="highlight">Vídeos <i class="fa fa-video-camera pull-right"></i></h3></li>
                    <li><a href="<?php echo $this->site_url('videos/mick-hill'); ?>"><i class="fa fa-film"></i> Mick Hill</a></li>
                </ul>
            </div>
        </div>  
        <div class="col col-sm-9">
            <div class="panel">
                <h1>Olá meu amor!!!</h1>
                <h5>Como vecê está? espero que bem.</h5>
                <p>Demorou mais terminei! aqui em baixo esta os videos que postei pra vc no outro site, é só clicar nos blocos com a descrição.</p>
                <img class="img-responsive" src="<?php echo $this->site_url('img/videos.jpg');?>">

                <hr>
                
                <h2 id="youtube">Vídeos do <i class="fa fa-youtube-play"></i> YouTube:</h2><br />
<?php
    foreach($this->videos_youtube as $video):
?>
                <a class="youtube" href="<?php echo $video['link']; ?>" title="Clique aqui!">
                    <div class="well">
                        <h4><?php echo $video['titulo']; ?> - <?php echo $video['data']; ?></h4>
                        <p class="text-muted"><?php echo $video['texto']; ?></p>
                        <p class="text-right">Clique aqui para ver o vídeo!</p>
                    </div>
                </a>
<?php
    endforeach;
?>
            </div>
      	</div> 
    </div>
</div>