<div class="container">
    <div class="row">
        <div class="col col-sm-3">
            <div class="">
                <ul class="nav bs-docs-sidenav">
                    <li><h3 class="highlight">Vídeos <i class="fa fa-video-camera pull-right"></i></h3></li>
<?php
    if ($this->links_lateral):
        foreach($this->links_lateral as $nome => $link):
            if ($link.'/' == $this->pagina_atual || $link == $this->pagina_atual) continue;
?>
                    <li><a href="<?php echo $link; ?>"><?php echo $nome; ?></a></li>
<?php
        endforeach;
    endif;
?>
                </ul>
            </div>
        </div>  
        <div class="col col-sm-9">
            <div class="panel">
                <h2 id="youtube">Vídeos do <i class="fa fa-youtube-play"></i> YouTube:</h2>
<?php
    if ($this->videos_youtube):
        echo '<br />';
        foreach($this->videos_youtube as $video):
?>
                <a class="youtube" id="<?php echo $video['slug']; ?>" href="<?php echo $video['link']; ?>" title="Clique aqui!">
                    <div class="well">
                        <h4><?php echo $video['titulo']; ?> - <?php echo $video['data']; ?></h4>
                        <p class="text-muted"><?php echo $video['texto']; ?></p>
                        <p class="text-right">Clique aqui para ver o vídeo!</p>
                    </div>
                </a>
<?php
        endforeach;
    else:
?>
                <h5 class="text-center well"><a>Não há vídeos cadastrados!!!</a></h5>
<?php
    endif;
?>
            </div>
      	</div> 
    </div>
</div>