        <!--Topo-->
        <nav class="navbar navbar-static navbar-fixed-top navbar-pad-original">
            <div class="container">
                <div class="navbar-header">
                    <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="#sobre" data-toggle="modal" class="navbar-brand" title="Sobre o site!"><?php echo $this->site_titulo; ?></a>
<?php
    if($this->site_uri[0] == $this->site_homepage):
?>
                    <a class="navbar-brand facebook-seguir">
                        <iframe
                            class="btn"
                            src="//www.facebook.com/plugins/follow?href=https%3A%2F%2Fwww.facebook.com%2Fpriscila.lima.31586&amp;layout=standard&amp;show_faces=true&amp;colorscheme=light&amp;width=450&amp;height=80"
                            scrolling="off"
                            frameborder="0"
                            allowTransparency="true"
                            >
                        </iframe>
                    </a>
<?php
    endif;
?>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
<?php
    if($this->usuario->status_login()):
        foreach ($this->links_menu as $NomeMenu => $Link):
            if($this->pagina_url != $Link)
                echo '<li><a href="' . $Link. '">';

            else
                echo '<li style="cursor: default; background-color: rgba(0, 0, 0, 0.15);"><a>';

            echo $NomeMenu . '</a></li>';
            
        endforeach;
?>
                        <li class="dropdown ">
                            <a style="cursor: pointer;" data-toggle="dropdown" class="dropdown-toggle"><span class="glyphicon glyphicon-user"></span> <b class="glyphicon glyphicon-chevron-down"></b></a>
                            <ul class="dropdown-menu">
                                <li class=""><a href="<?php echo $this->site_url('login/sair'); ?>"><span class="glyphicon glyphicon-log-out"></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sair do sistema&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(logout)</a></li>
                            </ul>
                        </li>
<?php
    elseif($this->site_uri[0] == $this->site_homepage):
?>
                        <li><a href="<?php echo $this->site_url('login'); ?>"><i class="glyphicon glyphicon-log-in"></i> Login</a></li>
<?php
    else:
?>
                        <li><a style="cursor: pointer" href="<?php echo $this->site_url;?>" ><i class="fa fa-mail-reply-all"></i> Voltar a inicial</a></li>
<?php
    endif;
?>
                    </ul>
                </div>
            </div>
        </nav>

        <!--Conteudo da página-->
        <div id="conteudo">
<?php
    if ($this->mensagem->status_exibicao()):
?>
            <!--Notificação-->
            <div class="page-alerts">
                <div id="alerta" class="alert alert-<?php echo $this->mensagem->tipo(); ?> page-alert" style="display: none;">
                    <button class="close" type="button"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <strong><?php echo $this->mensagem->titulo(); ?></strong> <?php echo $this->mensagem->texto(); ?>

                </div>
            </div>
<?php
    endif;
?>
